.ONESHELL:
.PHONY: FORCE
all: compile

compile: $(shell find . -name "*.java" -type f)
	- javac $^

run: FORCE
	- java

clean: FORCE
	- find . -name "*.class" -type f -delete

watch: FORCE
  git ls-files | entr make
